### ISSUE TITLE
CSSWG presentation of `scroll-start` notes

### ISSUE THREAD

**Issue by argyleink** [argyleink/ScrollSnapExplainers#19]
1. what is first layout?
1. what happens if display is toggled, etc, create/destroy?
1. #1339 interact notes
1. mention scroll padding/margin impact position
1. rtl/ltr, place-content interactions (align-content: can already do scroll end)
1. scroller in scroller?

**Comment by flackr** [comment]
Re 1. what is first layout, animations expose this to the developer. Animation objects are created and fire events when a box has its first layout.

**Comment by argyleink** [comment]
https://github.com/w3c/csswg-drafts/issues/6986#issuecomment-1028499159
- what happens if the element moves around or the scroller gets resized, does the scroll-start track along?
- what happens if the target position/element would put the scroller into an over or under extended scroll position?
