### ISSUE TITLE
[css-scroll-start] Call out interaction with scroll anchors

### ISSUE THREAD

**Issue by flackr** [argyleink/ScrollSnapExplainers#8]
When a scroll-start position is specified, it should be treated as the default initial scroll position. However, if a scroll anchor or other mechanism has a target it should be able to override the scroll-start. We should call this out in the explainer as another advantage.

**Comment by argyleink** [comment]
lemme know if you dont think i covered it well in the explainer! 

https://github.com/argyleink/ScrollSnapExplainers/blob/main/css-scroll-start/explainer.md#interactions-with-fragment-navigation

**Comment by flackr** [comment]
Looks good, thanks!
